services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: ./Frontend/sistema-notas
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./Frontend/sistema-notas:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis-data:/data

volumes:
  redis-data:
